### ISSUE TITLE
[NAVAIDS] LCA vor same name with LCA NDB

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#100]
στην BONEK1R αντι για VOR σου δειχνει οτι παει στο NDB. μηπως να το βαζαμε LCANDB το αλλο ή LCA2

**Comment by tasosb** [comment]
Δεν μπορει να φτιαχτει, δεν δινει την δυνατοτητα το GNG

**Comment by nakoale** [comment]
![870F3CF0-C00B-4584-8F8A-1C0EAD149A61](https://user-images.githubusercontent.com/19704019/80259667-d4175b80-868e-11ea-8d6c-0c49588605f3.jpeg)
ελεος μεχρι και αυτοι εχουν notam.
