### ISSUE TITLE
[COPX] IRBAX,FOXLI,NILAS

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#101]
Τα νεα copxes συμφωνα με τα νεα airway διαμορφωνονται ως εξης.
IRBAX (only dep) FL150 (δινουμε το μεγιστο μιας και το σημειο ειναι μονο για outbound)
FOXLI (only arr) FL140
NILAS (only dep) FL150 (δινουμε το μεγιστο μιας και το σημειο ειναι μονο για outbound)

**Comment by tasosb** [comment]
Ισχύει, αλλα τα IRBAX, FOXLI, NILAS είναι 4NM το ενα απο το άλλο. Άρα:
IRBAX - NILAS FL130
FOXLI FL140
Και έτσι είμαστε καλυμμένοι

**Comment by tasosb** [comment]
FOXLI added FL140
COPX at IRBAX changed from ARR to DEP
