### ISSUE TITLE
[COPX] AMANI gloCOPX

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#103]
**Description**

**Additional context**
Add any other context here.

**Comment by tasosb** [comment]
Υπάρχει σίγουρα θέμα; Ούτε το RIKSO βλεπω εχουμε αλλα τις συχνοτητες τις βγαζει σωστα στο handoff

**Comment by tasosb** [comment]
Αλεξανδρε αν ξαναβγαλει θεμα πες να το δω.
Σε εμενα δεν μου χει βγαλει ποτε θεμα με το LTBB/LTAA
