### ISSUE TITLE
[STAR] CODIC2DXILSZ instead of CODIC2GXILS Y

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#105]
αυτα τα ειχαμε ξαναφτιαξει για καποιο λογο σε αυτο το airac αλλαξαν.

**Comment by tasosb** [comment]
Για το CODIC Fixed. Το θέλουμε και για τα άλλα STAR?
FOXLI, LAKAD, NILAS?

**Comment by nakoale** [comment]
FOXLI , LAKAD , NILAS θελουν την ILSY μεσω DEXAS με τις G

**Comment by tasosb** [comment]
ΟΚ.
