### ISSUE TITLE
[COPX] KEPIR withdrawn. OGSIL instead. 

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#106]
Το KEPIR φευγει μαζι με το OLIDA. Ο νεος G8-N604 ειναι OGSIL-SOSIR-ATSOV-LSV-AMANI. Τα COPX για OGSIL ειναι τα ιδια με το KEPIR.

**Comment by tasosb** [comment]
Copx fixed
ASRs to be fixed

**Comment by tasosb** [comment]
ASRs (LGGG_APP.asr and LGAV_APP.asr) ==> Added OGSIL, removed KEPIR
