### ISSUE TITLE
[COPX] ATSOV,ERESO,BIFOK new COPX for LGMT

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#107]
ATSOV inbound FL90.
outbound FL140
ERESO inbound FL90
outbound FL140
BIFOK inbound FL80
outbound FL150

all values are according to minimum airway FLs from AIP.
The outbound value is the max value LGMT_APP can clear inside TMA.

**Comment by tasosb** [comment]
Inbound πιο χαμηλά απο outbound?
Συνταγή για conflict...

**Comment by tasosb** [comment]
All outbound FL80
All inbound FL90
Old COPXs to NILVA, MARIK, OLIDA removed
