### ISSUE TITLE
[BUG] Voice Channels Removed

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [hvacc/sector-file#112]
**Voice Channels Removed**
**Mε το καινούργιο update από το euroscope v3.2.1.24 έχει αφαιρεθεί από τις συχνότητες το voice Channel.**

**To Do**
Έτσι λοιπόν θα πρέπει και από το Sector μας να αφαιρεθεί το voice Channel στο αντίστοιχο section του GnG.

**Screenshots**
Παραθέτω φωτογραφίες πως θα πρέπει να είναι για να γλιτώσεις megabyte από το Sector και να είναι απόλυτα συμβατό το Sector με το καινούργιο update του Euroscope το v3.2.1.24
![Screenshot_7](https://user-images.githubusercontent.com/61604658/81754799-b4ba6400-94bf-11ea-89a9-a12904fcafd8.png)
![Screenshot_8](https://user-images.githubusercontent.com/61604658/81754801-b5eb9100-94bf-11ea-9000-45c3b3937a43.png)

**Additional context**
Αν χρειαστείς περαιτέρω πληροφορίες στείλε μου μήνυμα

.

**Comment by tasosb** [comment]
Βασιλη κατι είδα στο φορουμ τους, λένε το κρατανε για backwards compatibility - μιας που το r24 δεν θεωρείται "stable-beta". 
Είναι σωστή η σκέψη τους.
Άρα το αφηνουμε ετσι προς το παρον.
