### ISSUE TITLE
[STAR] PITAS 2J higher prioriry

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#113]
Η PITAS 2J καταληγει στο IAF BEDEX οπως και θα πρεπε. η STAR που ειναι περασμενη τωρα καταληγει στο DIREX. το ειχαμε φτιαξει παλια αλλα σε αυτο το airac ξαναχαλασε.

**Comment by Vasilis-Chalipilias** [comment]
H PITAS 2J  διορθώθηκε. Οι αλλαγές θα εμφανιστούν στο καινούργιο airac (2007)
![Screenshot_10](https://user-images.githubusercontent.com/61604658/84432572-ab92f300-ac35-11ea-8b02-8bd2ec59f987.jpg)
