### ISSUE TITLE
[STAR] TOBAL,ESERI,GIPRO,NORDI (1P) to be withdrawn

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#114]
Tα σημεια αυτα ειναι IAFs . Στο FMC δεν υπαρχουν η 1P οποτε δημιουργειται συγχυση στους πιλοτους. θα πρεπει να εμφανιζεται ΕSERI X ILSP και οχι ESERI X ESERI1P X ILP

**Comment by nakoale** [comment]
** To ιδιο ισχυει και για LCLK . SOBOS 1P , BOSIS 1P , ADLAS 1V (RNAV V 22)

**Comment by Vasilis-Chalipilias** [comment]
Διορθωσε με απο οσο τσεκαρα το fmc οταν πατας Αrrival χωρις star αλλα μονο Approach εμφανιζει ILS-29-P 
Οπου αυτη η διαδικασια εμφανιζει τα εξης: ESERI PH931 PH930 PH904 .
Αρα το σωστο ειναι να λεει το Sector ILSxP το ESERI φοτρωνεται απο το Approach.

**Comment by Vasilis-Chalipilias** [comment]
Τo **ESERI1P GIPRO1P NORDI1P TOBAL1P (LCPH)** οπως και τα **SOBOS1P BOSIS1P** ειναι [Approach Transition] και οχι STAR οποτε ο controller κανει cleared για **ILS29-P VIA ESERI1P Approach Transition**
Αν ο πιλοτος δεν τα γνωριζει να μαθει να σεταρει το fmc.
