### ISSUE TITLE
[AIRAC] LCCC new sectorization

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#117]
https://www.ead.eurocontrol.int/eadbasic/pamslight-EEC11A9EEB023658C5B06BEE477380F2/QXAPVEXICSKIQ/EN/Charts/ENR/AIRAC/LC_ENR_6_1-3_EN_2020-03-26.pdf

**Comment by nakoale** [comment]
http://prntscr.com/sma9nt

**Comment by nakoale** [comment]
http://prntscr.com/sma9nt

**Comment by Vasilis-Chalipilias** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/61604658/84544912-ec0e7180-ad06-11ea-9be2-d262ffba8f53.jpg)
DONE!
