### ISSUE TITLE
[COPX] NIKRO and MALED

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#118]
LGPZ_APP via MALED to LGKR_APP FL120
LGKR_APP via MALED to LGPZ_APP FL90

LGKR_APP is the next controller after LGPZ_APP via MALED

Outbounds from LGKR to NIKRO climb FL280 then

**Comment by Vasilis-Chalipilias** [comment]
Ενοεις για αδρια climb FL280 via Nikro με dep LGKR?
