### ISSUE TITLE
[LCCC - LCPH_GND to be included to as profile]

### ISSUE THREAD

**Issue by accgr4j** [hvacc/Sector-File#120]
**Description**
LCPH_GND to be include as default asr

**Comment by Vasilis-Chalipilias** [comment]
More details Please!!!

**Comment by Vasilis-Chalipilias** [comment]
@accgr4j  at **LCCC_CTR.ASR** Added **LCPH_GND** & LCLK_GND included **as default**!! to be released with **Airac 2109**
