### ISSUE TITLE
[Feature] LCRA ground layout for LCCC

### ISSUE THREAD

**Issue by accgr4j** [hvacc/sector-file#121]
https://www.aidu.mod.uk/aip/pdf/ad/LCRA-Akrotiri-Combined.pdf 

φιλε εδω ειναι τα charts. Επισης καλο θα ηταν αν μπορεσεις να βαλεις τα πιο πανω charts στο briefing! Χιλια ευχαριστω Bill!

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/129282478-19f03449-385c-4810-9b56-728cdb77d354.png)

https://briefing.hvacc.org  - LCRA CHARTS is ready to be published with Airac 2109 []
