### ISSUE TITLE
[SID] LGKF Priority ARA2T , GARTA & ROTSA 1T deps.

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#122]
**Description**

**Additional context**
Add any other context here.

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/129356297-10b0f2fa-d749-4690-8ef9-aeeb9eb97c4b.png)

Done! - **in the next update Airac 2109 SEP**
