### ISSUE TITLE
Procedure Missing 

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [hvacc/Sector-File#123]
LGSO - LGML - circling approach missing

**Comment by Vasilis-Chalipilias** [comment]
Για την ωρα θα κλισει το Issue και θα το δουμε σε δευτερο χρονο

**Comment by Ioannis-G** [comment]
![image](https://github.com/user-attachments/assets/b51f5bd0-4d68-4fa1-a49c-49606dd6bc03)
![image](https://github.com/user-attachments/assets/97e8f7e6-6eff-42d6-8dc2-0c387c40d4a0)
