### ISSUE TITLE
[PROFILES] AFIS airport positions to be renamed

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#124]
AFIS airport profiles are currently defined as Tower, eg. Syros Tower.

Proposal -> Such positions to be defined as Information (AFIS), eg. Syros Information

AFIS airports:
LGIK
LGKP
LGKS
LGKY
LGLE
LGML
LGNX
LGPA
LGPL
LGSO
LGST
LGKA
LGKC
LGKZ
LGKJ

**Comment by Vasilis-Chalipilias** [comment]
Profiles Corrected to be release with **Airac 2109**
