### ISSUE TITLE
[PROFILES] LGGG-U_CTR and LGMD-U_CTR profiles missing by default

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#125]
In order to control as LGGG-U_CTR and LGMD-U_CTR you should create your own profile for the positions. It would be better if these profiles are included by default in the Profiles.txt file. [Not the frequencies, the profiles]

**Comment by Vasilis-Chalipilias** [comment]
Profiles is ready to be released with **Airac 2109**
