### ISSUE TITLE
[COPX] PIKAD inbound LGAV FL250

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#128]
**Description**

**Comment by Vasilis-Chalipilias** [comment]
ΑΠΟ **PIKAD** ΓΙΑ **LGAV** descent **FL250**??????  επιβεβαίωσε μου λιγο αν αυτο εννοεις??

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/130655560-4d45fcac-cfd8-4c8e-b53b-7cf0296fd31c.png)

**Comment by Vasilis-Chalipilias** [comment]
> ΑΠΟ **PIKAD** ΓΙΑ **LGAV** descent **FL250**?????? επιβεβαίωσε μου λιγο αν αυτο εννοεις??

**Comment by nakoale** [comment]
ναι ναι

**Comment by Vasilis-Chalipilias** [comment]
Ευχαριστω added to be released Airac 2109
