### ISSUE TITLE
[NAV Glo COPX] - [COPX - LGGG]

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [hvacc/Sector-File#143]
**LBSR->LGMD dest LGMT,LGLM FL330
LGMD->LTAA dest LTFE FL310
LTAA->LGMD dep LTFE FL300
LGMD->LTAA dep LGAV dest LTFM FL330 **

**Comment by nakoale** [comment]
LGMT,LGLM (via NIKTI)
LTFE (via RIKSO,VEXOL)
LTFM ( via AMANI)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/151674626-6d65ef26-8988-40af-845e-cae284daf5b9.png)

![image](https://user-images.githubusercontent.com/61604658/151674804-a21201bd-6bd4-4ba2-9ed7-71785aace8f9.png)

![image](https://user-images.githubusercontent.com/61604658/151674811-1e41bd4c-1e32-4cdf-a7ca-a51348e4fe86.png)

![image](https://user-images.githubusercontent.com/61604658/151674814-50be0278-608b-4d20-b4c6-fbdf8c1bcd58.png)

![image](https://user-images.githubusercontent.com/61604658/151674916-989a6667-ad79-47af-ae6f-4f3e2389e6cf.png)
