### ISSUE TITLE
[NAV Positions]-[ATC COMMUNICATION freq - Changes]

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [hvacc/Sector-File#146]
**LGAV_DEL  -  Venizelos Delivery  -  FREQ From 118.675 to 118.680 
LGAV_GND -  Ground - FREQ from 121.750 to 121.755**

**New Position 
LGAV_S_GND -  Ground South - FREQ - 121.955**
______________________________________________________________________

**LGKR_GND - Kerkira Ground       - FREQ  - 121.700         -             121.705 
LGKR_TWR - Kerkira Tower         - FREQ  - 120.850          -             120.855 
LGKR_F_APP - Kerkira Director  - FREQ   - 118.075          -            118.080 
LGKR_APP - Kerkira Radar         - FREQ   - 122.350          -            122.355 
LGKR_ATIS -  Atis                        -  FREQ  - 126.350          -             126.355** __________________________________________________________________________________

**LGRP_GND - Diagoras Ground - FREQ - 121.700  - 121.705**

**Comment by SpyrosTTK** [comment]
Two more additions to be added, if possible: (New positions)

LGAV - Venizelos Ground South  - FREQ - 121.955
LGAV - Athinai Arrival East - FREQ - 126.575
