### ISSUE TITLE
[SECTOR] New sub-sector LGAV_P_GND (Ground Planner)

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#151]
It controls taxiways A and B and the taxilinks between them. It controls D and the taxilinks from D1 to D10. It manages the flow either of the departures or the arrivals in coordination with Tower/Ground.  LGAV_P_GND [GAP] FREQ : 121.800 
![Screenshot_2](https://user-images.githubusercontent.com/19704019/155835726-9325e5ff-089d-4e2a-904e-5841d4e3886b.png)

**Comment by nakoale** [comment]
Ground

**Comment by Vasilis-Chalipilias** [comment]
Σκετο?

**Comment by Vasilis-Chalipilias** [comment]
Θα Μπερδευονται

**Comment by Vasilis-Chalipilias** [comment]
Γραψτε μου, τι βελτιωσεις θελει.

**Comment by SpyrosTTK** [comment]
Θέλει δουλειά όλο το ground της Αθηνάς από την αρχή (αφού τώρα έχουν φτιαχτεί sector πάνω σε άλλα sector και όταν είναι ανοιχτά τα πάντα δεν φαίνονται σωστά). Οπότε το ground της Αθήνας πρέπει να χωριστεί σε 4 sectors
![image](https://user-images.githubusercontent.com/79931000/158895152-53f21b35-3c85-4da4-9aad-bd3623782bd7.png)
Άρα το LGAV_GND όταν ανοίγει θα ελέγχει και τα 4
Όταν ανοίγει το LGAV_S_GND θα ελέγχει μόνο το κομμάτι του  (βλέπε εικόνα) και όχι και τα taxiways
Όταν ανοίγει το LGAV_P_GND θα ελέγχει τα δύο sector του
Ο τρόπος αυτός με τα sectors στο ground είναι πολύ ασφαλής και αποτελεσματικός
Για να γίνει σωστά, προφανώς δεν βιαζόμαστε να βγουν οι αλλαγές με το airac στις 24 Μαρτίου

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/159011583-e8abf697-acc1-4fb3-98a1-3ca0b160da13.png)

Αυτο το τελικο σχεδιο μου αν συμφωνειτε ξεκιναω

**Comment by SpyrosTTK** [comment]
Τέλειο! προχώρα το

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/159068207-887b8f73-2783-4a8e-a4d2-d0b4492406dd.png)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/159086868-af00caf8-48fd-41fe-b15f-626f089aca9d.png)

LGAV_S_GND

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/159093368-2341fece-4ecb-422f-ba2f-a70abd55c23f.png)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/159093435-02d88138-abe2-4fd9-b1b0-cb043e2f7171.png)
LGAV_GND_03R21L

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/159093472-898d72bd-92b1-4de9-b3ef-39957bc3ccfd.png)
LGAV_P_GND

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/159093644-90d64bc8-bf81-4545-888f-d4ce49bb9a16.png)
LGAV_GND

**Comment by Vasilis-Chalipilias** [comment]
DONE!
