### ISSUE TITLE
[BUG] LGMD-T & LGMD-K border line

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#152]
LGMD-T and LGMD-K borders displayed in the wrong way?
![image](https://user-images.githubusercontent.com/79931000/155902515-7f4aca77-939f-447d-8673-6e86bb8981c1.png)
![image](https://user-images.githubusercontent.com/79931000/155902684-9ed8dd98-4f2d-4389-840f-2697e5763862.png)
As you see the active sector is displayed correctly but the line is off
(1st picture with my settings and the 2nd one is the default sector file)

**Comment by Vasilis-Chalipilias** [comment]
Spuros How do you enable the Sectoration of LGGG?

1. upload a screenshot of checked box of Display settings to be able find the corrent region format.

**Comment by SpyrosTTK** [comment]
![image](https://user-images.githubusercontent.com/79931000/156702115-e26f0297-bbc4-46b1-9b5f-e8cebaaf34ba.png)

**Comment by nakoale** [comment]
bill απλα θελει ανανεωση το LGGG SECTORIZATION δεν το ειχαμε ανανεωσει οταν αλλαξαμε τα sectors LGMD T και LGMD K

**Comment by Vasilis-Chalipilias** [comment]
TRUE!

**Comment by Vasilis-Chalipilias** [comment]
Ετοιμο!

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/159094091-3e66feab-d58a-496d-b5aa-2d41d672ec6e.png)

**Comment by Vasilis-Chalipilias** [comment]
DONE!
