### ISSUE TITLE
[SECTOR]New sub-sector LGAV_E_APP

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#153]
LGAV_E_APP (ARR4) FREQ : 126.575
![Screenshot_2](https://user-images.githubusercontent.com/19704019/156549272-b8b11f7f-c69d-4cfb-bb41-3e092693c378.png)

**Comment by SpyrosTTK** [comment]
Freq 126.575 confirmed
119.1 is used as backup approach freq

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/160701157-43b31c8f-013c-4d1a-8f05-4faae58e6385.png)
