### ISSUE TITLE
[NAV Positions]-[ATC COMMUNICATION freq - Changes- FALLBACK]

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [hvacc/Sector-File#155]
**### Due to spacing of 8.33khz will be going back to previous freq**

LGAV_GND - Ground - FREQ from 121.755 TO **121.750**

LGAV_S_GND - Ground South - FREQ - 121.955 to **121.950**

LGAV_DEL Delivery - FREQ from 118.680 to **118.675**

_____________________________________________________________________

LGKR_GND - Kerkira Ground - FREQ -121.705 **121.700**
LGKR_TWR - Kerkira Tower - FREQ - 120.855 - **120.850**
LGKR_APP - Kerkira Radar - FREQ - 122.355 - **122.350**
LGKR_ATIS - Atis - FREQ - 126.355 - **126.350**

LGRP_GND - Diagoras Ground - FREQ - 121.705 - **121.700** 

LGKR_F_APP Kerkira Director - FREQ from 118.080 to **118.075**

**Comment by SpyrosTTK** [comment]
LGAV_DEL Delivery - FREQ from 118.680 to 118.675

LGKR_F_APP Kerkira Director - FREQ from 118.080 to 118.075

**Comment by Vasilis-Chalipilias** [comment]
@SpyrosTTK  ΑΥΤΑ ΜΟΟΥ ΕΙΠΕΣ ΟΤΙ ΔΟΥΛΕΥΟΥΝ

**Comment by SpyrosTTK** [comment]
Και αυτές οι συχνότητες έχουν 8.33kHz spacing, οπότε καλύτερα όλες να γυρίσουν στο 25kHz spacing, γιατί και πάλι μπορεί να παρουσιαστεί κάποιο θέμα.

**Comment by Vasilis-Chalipilias** [comment]
OK

**Comment by Vasilis-Chalipilias** [comment]
LGGG Update - Package Release 2202/v1 **FIX**

**Comment by Vasilis-Chalipilias** [comment]
Replace
