### ISSUE TITLE
[COPX] ELIKA COPX FL180 outbound OLBA . same for DAFNA (LLBG)

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#169]
The FIX before for ELIKA copx does not exist (should put OLBA)

The FIX before for DAFNA copx does not exist (should put LLBG)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/169646441-232e3b4e-1b2a-4702-af44-9ca5adbde0c6.png)
