### ISSUE TITLE
[COPX] ELIKA and DAFNA copx

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#175]
το ELIKA το εχεις 2 φορες (μια με fix before LLBG και μια με OLBA - αυτο με το LLBG σβηστο τελειως) και επισης το DAFNA δεν το εφτιαξες απο το προηγουμενο airac. πρεπει στο DAFNA να βαλεις fix before LLBG.

**Comment by Vasilis-Chalipilias** [comment]
Ετοιμο

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/175809286-5891a2d5-a79b-41fd-bf23-9d9a2d87ee5c.png)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/175809294-1c9d17aa-d041-4ba7-bf53-8deea2016ce0.png)
