### ISSUE TITLE
[BUG] Malta LMMM not recognized

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#184]
Όταν ανοίγει LMMM_CTR δεν αναγνωρίζεται

**Comment by Vasilis-Chalipilias** [comment]
Copy that το ελεγχω δεν εχω βγαλει ακρη καποιος δεν ειναι απο εμας το προβλημα θα εποικινωνησω με τους ιταλους
αν εχεις καποιο mail απο γειτονες πες μου

**Comment by Vasilis-Chalipilias** [comment]
Θελω βοηθεια γιαυτο το bug με on hold

**Comment by Vasilis-Chalipilias** [comment]
Το τσεκαρα με τους Ιταλους ειναι στο ελεγχο τους και δουλευει κανονικα!@
