### ISSUE TITLE
[BUG] Duplicate VARIX and all the Fir points

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#193]
![image](https://user-images.githubusercontent.com/79931000/194756684-65ad38d6-0f14-43c1-863b-98761fbac172.png)

**Comment by Vasilis-Chalipilias** [comment]
Γραψε μου αναλυτικα δεν καταλαβαινω

**Comment by Vasilis-Chalipilias** [comment]
Will be fixed in the next 2 AIRAC from LIDO.
