### ISSUE TITLE
[APP] δεν υπαρχει το APP μεσω KAM για ILS 35L , ουτε για VOR 17R

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#198]
ΚΑΛΟΕΙΝΑΙ ΝΑ ΤΑ ΠΕΡΑΣΟΥΜΕ ΟΛΑ ΤΑ ΑΕΡΟΔΡΟΜΙΑ ΕΝΑ ΤΣΕΚ. ΓΙΑΤΙ ΠΑΙΖΕΙΝΑ ΒΡΟΥΜΕ ΚΑΙ ΑΛΛΑ ΟΠΩΣ ΜΕ ΤΗ ΣΑΝΤΟΡΙΝΗ ΚΑΙ ΤΗΝ ΚΑΛΑΜΑΤΑ

**Comment by Vasilis-Chalipilias** [comment]
Θα τα ελεγχω ολα να νακο απλα θελω να γνωριζεις οτι κατι συμβαινει και δυσλτουργει αυτες τις διαδικασιες τις ειχαμε παλια αλλαζουν οι ονμασιες και εξαφανιζονται θελει προσοχη και αναζητησει απο μερια μου να ελεγχω συνεχεια γιαυτο καλο ειναι να κανουν ολοι οι ελεκτες report

**Comment by Vasilis-Chalipilias** [comment]
**VOR W RWY 17R**
![image](https://user-images.githubusercontent.com/61604658/205412246-26dd02bd-7052-4b80-a5dc-468f5d3024f1.png)

**Comment by Vasilis-Chalipilias** [comment]
**VOR Z RWY 35R**
![image](https://user-images.githubusercontent.com/61604658/205412410-5c274cf4-0732-4b2a-b6d3-ca45152d9c78.png)

**Comment by Vasilis-Chalipilias** [comment]
**ALL WITH AN ILS Z RWY 35L**
![image](https://user-images.githubusercontent.com/61604658/205413011-49d7e249-ddab-4947-91e7-eea5cbdd4888.png)
