### ISSUE TITLE
[BUG] LGGG FIR LINES BUGGING due to LTXX NO Permited Changes

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [hvacc/Sector-File#207]
![image](https://user-images.githubusercontent.com/61604658/206319801-d8068ffb-50e8-4c1f-be9f-2a035d50b6d5.png)

**Comment by SpyrosTTK** [comment]
Coordinated with TRvACC. Bugs fixed.
Implemented new Ankara sectorization
![image](https://github.com/hvacc/Sector-File/assets/79931000/11e4285e-ff50-4efb-b1f5-c4774b514410)
![image](https://github.com/hvacc/Sector-File/assets/79931000/2e0660ef-dce9-4ea1-844c-0b563430493e)
![image](https://github.com/hvacc/Sector-File/assets/79931000/a3ed923b-8009-40f7-a9eb-e2dbf1591e50)
![image](https://github.com/hvacc/Sector-File/assets/79931000/a7bff68a-9d24-4c0b-b3f6-2e822fb78566)
![image](https://github.com/hvacc/Sector-File/assets/79931000/1f473cfe-9cf1-4070-b299-c69654de23c2)
