### ISSUE TITLE
[SECTOR] LCCC-E_LOW sector

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#211]
implementation of Nicosia east low sector with frequency 127.075 . GND- FL305!!

**Comment by nakoale** [comment]
355656N0330000E    LCA     340628N 0334118E   340654N 0343928E

**Comment by Vasilis-Chalipilias** [comment]
![Screenshot_222](https://user-images.githubusercontent.com/61604658/216759410-20c97466-42ab-4bf4-a104-556c19c1870c.jpg)
