### ISSUE TITLE
[COPX] REVISED copx XAVIS/GIVIS/LABUX/DELAV/SIT/ NAVUS

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#215]
Συμφωνα με το LOA 2018

for LGIR
inbound FL130 via XAVIS/GIVIS +LGST
inbound FL160 via SIT/LABUX/DELAV
inbound FL130 via NAVUS and outbound FL120

for LGSA 

inbound FL160 SIT

**Comment by Vasilis-Chalipilias** [comment]
XAVIS 110 - 130

**Comment by Vasilis-Chalipilias** [comment]
GIVIS 110 - 130

**Comment by Vasilis-Chalipilias** [comment]
SIT 140 -160

**Comment by Vasilis-Chalipilias** [comment]
LABUX 120 - 160

**Comment by Vasilis-Chalipilias** [comment]
DELAV 120 - 160

**Comment by Vasilis-Chalipilias** [comment]
NAVUS 110 - 130
