### ISSUE TITLE
[COPX] REVISED copx for LGRP

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#216]
LOKNA           INB FL170       OUTB FL160
ROXOL                   FL170                FL160
LAKAD                   FL170                FL180
NILAS                    FL170                FL180
ORVIS                   FL170                 FL180
NAVOK                 δεν εχει              FL170

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/218826358-e3c351c0-c14f-43d6-9ee2-5d689127f352.png)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://user-images.githubusercontent.com/61604658/218827066-f3388e8d-2bfc-4447-a6dd-42c2d1c8e6f8.png)
