### ISSUE TITLE
[COPX] delete

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#232]
FIR_COPX:*:*:TSL:*:*:LWSS·LWSS·325·999:LGGG·LGGGTSL·325·600:*:*:TSL   | **STBY**

FIR_COPX:*:*:ELPIS:*:*:LWSS·LWSS·325·999:LGGG·LGGGTSL·325·600:*:*:ELPIS  **STBY**

FIR_COPX:*:*:PIKOS:*:*:LAAA·LAAA·325·660:LGGG·LGGGTSL·325·600:*:*:PIKOS  **STBY**

COPX:LGKF:*:ASTUS:*:*:LGGG·LGAD_APP·000·155:LGGG·LGGGKFN·125·155:14000:*:ASTUS  **STBY**
COPX:LGZA:*:ASTUS:*:*:LGGG·LGAD_APP·000·155:LGGG·LGGGKFN·125·155:14000:*:ASTUS  **STBY**
COPX:LGZA:*:LASKO:*:*:LGGG·LGAD_APP·000·155:LGGG·LGGGKFN·125·155:14000:*:LASKO    **STBY**
COPX:LGKF:*:LASKO:*:*:LGGG·LGAD_APP·000·155:LGGG·LGGGKFN·125·155:14000:*:LASKO  **STBY**

**Comment by SpyrosTTK** [comment]
checked good to go
