### ISSUE TITLE
[SID] BONEK2W higher priority than BONEK2D (LCLK/rwy 04)

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#236]
το χαμε φτιαξει υποτιθεται στις με τα προηγουμενα airac και τωρα παλι τα ιδια.

**Comment by Vasilis-Chalipilias** [comment]
![image](https://github.com/hvacc/Sector-File/assets/61604658/45d8c700-54ce-4e9e-b1a7-b63be75f5cdc)
