### ISSUE TITLE
[Feature] LGSM | PROCEDURE ADDED VOR-DME AND STAR

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [hvacc/Sector-File#241]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you suggest**
A clear and concise description of what you want to change.

**Additional context**

**Comment by Vasilis-Chalipilias** [comment]
![image](https://github.com/hvacc/Sector-File/assets/61604658/3d89608a-f503-4517-9ff0-a57df973f8f6)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://github.com/hvacc/Sector-File/assets/61604658/080c7c34-5e7d-4147-bef8-1441e13524ba)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://github.com/hvacc/Sector-File/assets/61604658/21304440-6f91-436a-ac14-bde49c4c1e9a)

**Comment by Vasilis-Chalipilias** [comment]
![image](https://github.com/hvacc/Sector-File/assets/61604658/352c624c-558d-42c2-a0fb-8f0c3ca65699)

**Comment by SpyrosTTK** [comment]
Μπόμπα
