### ISSUE TITLE
[ATIS] LGKV ATIS FREQ IN LOGON PROFILES

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#242]
Add to LGKV_APP and LGKV_TWR
ATIS on 128.150

**Comment by Vasilis-Chalipilias** [comment]
PROFILE:LGKV_TWR:50:4
ATIS2:Megas Alexandros Tower
ATIS3:ATIS on 128.150 - Charts on briefing.hvacc.org
ATIS4:Feedback on vats.im/gr/atcfb
