### ISSUE TITLE
[BUG] LGIR STAND NUMBERS

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#244]
REMOVE G DESIGNATORS FROM LGIR STANDS
T STANDS REMAIN THE SAME

**Comment by Vasilis-Chalipilias** [comment]
https://prnt.sc/z7WwMGz3NkQB @SpyrosTTK

**Comment by Vasilis-Chalipilias** [comment]
Rebuilded some gates according to Airac
