### ISSUE TITLE
[BUG] RECONSTRUCTION OF LGAV APP/TWR/GND

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#252]

**Comment by SpyrosTTK** [comment]
4 sectors by names:
Ground North
Ground South
Ground West
Ground East

LGAV_GND controls North & South
LGAV_S_GND controls only South
LGAV_P_GND controls East & West

LGAV_TWR controls East & West
LGAV_W_TWR controls West
If LGAV_P_GND is offline

**Comment by SpyrosTTK** [comment]
4 sectors by names:
Ground North
Ground South
Ground West
Ground East

LGAV_GND controls North & South
LGAV_S_GND controls only South
LGAV_P_GND controls East & West

LGAV_TWR controls East & West
LGAV_W_TWR controls West
If LGAV_P_GND is offline

**Comment by SpyrosTTK** [comment]
Approach Sectorization

Two sectors by names:
ATHINAI TMA WEST
ATHINAI TMA EAST

LGAV_APP controls West and East
LGAV_E_APP controls East

LGAV_F_APP and LGAV_DEP remain the same

**Comment by Vasilis-Chalipilias** [comment]
need to re-sectorize or reorganize the responsibilities of controllers in the Athena terminal area, it typically involves changes in how the airspace is divided and controlled to optimize efficiency and safety. The exact reasons and procedures for re-sectorization can vary depending on air traffic demand, airport layout, and other operational factors.

**Comment by Vasilis-Chalipilias** [comment]
LGAV_GND_03L21R     -    LGAV_W_GND 
LGAV_GND_03R21L     -    LGAV_E_GND
LGAV_GND                   -   LGAV_N_GND

**Comment by Vasilis-Chalipilias** [comment]
LGAV GND - RE SECTORAZION COMPLED

**Comment by Vasilis-Chalipilias** [comment]
LGAV APP - IS OK
lgav_E_APP - PRBLEM ΑΝΑΒΕΙ ΤΟΝ ΕΑΥΤΟ ΤΟΥ ΓΥΡΟ ΓΥΡΟ

**Comment by SpyrosTTK** [comment]
Resectorization Complete, to be published with AIRAC 2310
