### ISSUE TITLE
[POSITIONS] Callsign and Frequency changes for AIRAC 2311

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#269]
All Callsign and Freq changes are presented in detail in https://1drv.ms/x/s!AlIAg7U6Y7BTvQAz_PnTFnsam6Y0?e=fMBnKW

**Comment by SpyrosTTK** [comment]
Completed! Sectors as well. All checked.

**Comment by Vasilis-Chalipilias** [comment]
AFV REMAINING
