### ISSUE TITLE
[BUG] AFV LGIR -LGKP

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#281]
ΝΑ ΣΥΜΠΕΡΙΛΑΒΟΥΜΕ ΣΤΟ LGIR-APP την κεραία της Καρπάθου

**Comment by Vasilis-Chalipilias** [comment]
![image](https://github.com/hvacc/Sector-File/assets/61604658/2014acb9-ce86-4c6d-83d7-380d8a918189)

DONE
