### ISSUE TITLE
[Feature] AIRAC | LGIR TMA EXPANSION | (KARPATHOS AREA) AIRAC 2403

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#282]
RECONTRUCTION OF LGIR TMA . INCL. KARPATHOS AREA WITH MRVAS.

**Comment by Vasilis-Chalipilias** [comment]
θελω λεπτομεριες

**Comment by Vasilis-Chalipilias** [comment]
![image](https://github.com/hvacc/Sector-File/assets/61604658/11fee677-718c-4849-b0b9-daae4feaaaee)
