### ISSUE TITLE
[AIRAC] Added | LGAV – ATHINAI/ ELEFTHERIOS VENIZELOS | NEW | PROCEDURES | RNP

### ISSUE THREAD

**Issue by Vasilis-Chalipilias** [hvacc/Sector-File#296]
**Added | LGAV – ATHINAI/ ELEFTHERIOS VENIZELOS | NEW | PROCEDURES | ILS  - RNP**

Instrument Approach Chart (IAC) – ICAO: - **ILSz or LOCz RWY 21R**   | 21 MAR 24 AD 2-LGAV-IAC-14
Instrument Approach Chart (IAC) - ICAO: - **ILS X CAT I & II RWY 03L**   | 21 MAR 24 AD 2-LGAV-IAC-22
Instrument Approach Chart (IAC) - ICAO: - **ILS X CAT I & II RWY 03R**  | 21 MAR 24 AD 2-LGAV-IAC-23
Instrument Approach Chart (IAC) - ICAO: - **ILS X CAT I & II RWY 21L**   | 21 MAR 24 AD 2-LGAV-IAC-24
Instrument Approach Chart (IAC) - ICAO: - **ILS X CAT I & II RWY 21R**   | 21 MAR 24 AD 2-LGAV-IAC-25

Instrument Approach Chart (IAC) - ICAO: - **RNP RWY 03L**  | 21 MAR 24 AD 2-LGAV-IAC-26
Instrument Approach Chart (IAC) - ICAO: - **RNP Z RWY 03R**  | 21 MAR 24 AD 2-LGAV-IAC-27
Instrument Approach Chart (IAC) - ICAO: - **RNP Y RWY 03R**  | 21 MAR 24 AD 2-LGAV-IAC-28
Instrument Approach Chart (IAC) - ICAO: - **RNP RWY 21L**   | 21 MAR 24 AD 2-LGAV-IAC-29
Instrument Approach Chart (IAC) - ICAO: - **RNP RWY 21R**   | 21 MAR 24 AD 2-LGAV-IAC-30

Standard Instrument Departure  Chart (IAC) - ICAO: - **RNAV RWY 03R**  | 21 MAR 24  AD 2-LGAV-SID-15
**BIBEX1E, DDM1E, KEA1E, KOR1E, KRO1E, ROPOX1E**

Standard Instrument Departure  Chart (IAC) - ICAO: - **RNAV RWY 03L**  | 21 MAR 24  AD 2-LGAV-SID-16
**BIBEX1H, DDM1H, KEA1H, KOR1H, KRO1H, ROPOX1H**

Standard Instrument Departure  Chart (IAC) - ICAO: - **RNAV RWY 21R**  | 21 MAR 24  AD 2-LGAV-SID-17
**BIBEX1M, DDM1M, KEA1M, KOR1M, KRO1M, ROPOX1M**

Standard Instrument Departure  Chart (IAC) - ICAO: - RNAV RWY 21L  | 21 MAR 24  AD 2-LGAV-SID-18
**BIBEX1N, DDM1N, KEA1N, KOR1N, KRO1N, ROPOX1N**

Standard Instrument Arrival  Chart (IAC) - ICAO: - **RNAV RWY 03 L/R**  | 21 MAR 24  AD 2-LGAV-STAR-4
**ASTOV1Q, BADEL1K, BADEL1Q, BIBEX1Q, NEMES1Q, NEVRA1Q, OGSIL1Q, PIKAD1Q, RILIN1Q, ROPOX1K, ROPOX1Q, SOREV1Q, VARIX1Q, VELOP1Q, XORKI1K, XORKI1Q**

Standard Instrument Arrival  Chart (IAC) - ICAO: - **RNAV RWY 21 L/R**  | 21 MAR 24  AD 2-LGAV-STAR-5
**ASTOV1R, ASTOV1W, BIBEX1W, NEMES1R, NEMES1W, NEVRA1W, OGSIL1W, PIKAD1R, PIKAD1W, RILIN1R, RILIN1W, ROPOX1W, SOREV1W, VARIX1R, VARIX1W, VELOP1W, XORKI1W**

**Comment by SpyrosTTK** [comment]
PRIORITIES
STARs

03s | Q->K->C->P
21s | W->R->A->B

SIDs

03R | E->T->J
03L | H->L & D->N & K
21R | M->G
21L | N->F

Approaches

All RWYs || ILS X -> RNP (for 03R RNP Y over RNP Z) -> ILS Z -> ILS Y (except 21R where ILS Y does not exist)

Notes
In Euroscope only the star name is required. Thus, all RNAV STARs will be combined with ILS X of all RWYs, which has the same points as the RNP approaches. If an a/c requests a different approach other than ILS X or RNP, no further action from ES is needed (controller will accomodate the a/c)

For SIDs priorities are essential. For non-RNAV equiped a/c, controllers will assign the old procedures, so again no automatic action from ES is needed
