### ISSUE TITLE
[BUG] Fix KEA Coordinates

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#303]
Fix KEA coordinates and possible Duplicates.

Reference: ENR 4.1, LGAV-VFR

**Comment by SpyrosTTK** [comment]
Μήπως το VFR να γίνει V.KEA?
Γιατί το IFR χρειάζεται για το Approach

**Comment by Ioannis-G** [comment]
Ίσως καλύτερα KEA.V ή KEA.VFR για να μην «χαλάσει» η αλφαβητική σειρά στο SCT.

**Comment by SpyrosTTK** [comment]
Σωστό, δικό σου

**Comment by Ioannis-G** [comment]
![Στιγμιότυπο οθόνης 2024-04-08 230018](https://github.com/hvacc/Sector-File/assets/113134133/45e564e7-f36d-4910-b14b-64aadfe4436f)

![Στιγμιότυπο οθόνης 2024-04-08 230037](https://github.com/hvacc/Sector-File/assets/113134133/932d9a54-09f0-416e-9aee-b5bdc8aeb80a)
