### ISSUE TITLE
[AIRAC] 2405 NISYROS Coordinates

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#304]
Reference AMDT 04/24 LGRP VFR

**Comment by Ioannis-G** [comment]
![image](https://github.com/hvacc/Sector-File/assets/113134133/d6d3ffde-e092-48d9-9342-cba2e9845054)

![image](https://github.com/hvacc/Sector-File/assets/113134133/c3ac2181-413e-49ad-9ee6-2d920b887f16)


Η Σωστή συντεταγμένη είναι ήδη περασμένη, αλλά το point είναι περασμένο διπλό.
