### ISSUE TITLE
[GND Networks] LGTS | Rework Network to Current Airport Layout

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#311]
Current network is based on old layout. Update required to current layout due to training

**Comment by Ioannis-G** [comment]
Rwy Exits Completed and Tested

**Comment by Ioannis-G** [comment]
Stands 1-26, Taxiway C and Taxiway D Completed and Tested.

**Comment by Ioannis-G** [comment]
Taxiway A and taxiways connecting  to A completed and tested.
