### ISSUE TITLE
[POSITIONS] Revision of Athinai and Makedonia ACC Positions

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#313]
https://1drv.ms/x/s!AlIAg7U6Y7BTvlGIKhSH0pDyua1Z?e=BXmKPb

Changes documended here. Start time: Sat, 20 Apr

**Comment by Ioannis-G** [comment]
CC: #314

**Comment by SpyrosTTK** [comment]
https://docs.google.com/spreadsheets/d/1-13teAn-PAGAFgwmkfeDSBycjQcspmi3/edit?usp=sharing&ouid=106861122859681773865&rtpof=true&sd=true
