### ISSUE TITLE
[SECTOR] Change ownership in respect to new positions and priorities

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#314]
Positions in: https://1drv.ms/x/s!AlIAg7U6Y7BTvlGIKhSH0pDyua1Z?e=BXmKPb

Priorities in: https://1drv.ms/w/s!AlIAg7U6Y7BTvleGaExdA4sKTqPA?e=xZXZbq

LGGG and LCCC

**Comment by Ioannis-G** [comment]
CC: #313
