### ISSUE TITLE
[AIRAC] CTR Check with 2405

### ISSUE THREAD

**Issue by SpyrosTTK** [hvacc/Sector-File#318]
Change effective with AIRAC 2405

**Comment by Ioannis-G** [comment]
Changed CTR Upper Vertical Limits:

LGEL_TWR from 050 to 040
LGKR_TWR from 050 to 100
LGKV_TWR from 050 to 080
LGMK_TWR from 050 to 060
LGRP_TWR from 050 to 100
LGTS_TWR from 050 to 100
LGTL_TWR from 050 to 040
LGTG_TWR from 020 to 050

Changed LGTS_TWR radius definition from 10.5nm to 10nm

Added LGPZ_TWR and LGSY_TWR Sectors.

Added displays to LGKP_TWR and LGMK_TWR Sectors.
