### ISSUE TITLE
[COPX] FREE COPX EKTOS / IXIMA

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#347]
KRK -> MIL

**Comment by Ioannis-G** [comment]
![image](https://github.com/hvacc/Sector-File/assets/113134133/ca1c7059-a052-49a9-8ffc-9f6dbee6eea8)
![image](https://github.com/hvacc/Sector-File/assets/113134133/afe76659-9fcd-46da-a13e-3f63fc727fa4)
