### ISSUE TITLE
[BUG] LGKR | Coordination Request for KR602/KR164 when Tower is Online

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#358]
να μην ερχεται copx approval στον πυργο οταν δινει direct το LGKR APP. σαν τα AV στην αθηνα που τα διορθωσαμε.

**Comment by Ioannis-G** [comment]
![image](https://github.com/user-attachments/assets/1087d548-54a5-4db0-9693-d72cab6763cd)
