### ISSUE TITLE
[BUG] PROC | LGTS | No Priority for MKR-based SIDs for Runway 10

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#373]
βγαζει την 1G με προτεραιοτητα αντι για την 1C ,απο τον 10 στη ΘΕΣ/ΝΙΚΗ

**Comment by Ioannis-G** [comment]
Διορθώθηκε!
![image](https://github.com/user-attachments/assets/596eb689-3d7e-43d0-940d-93a016c1b83a)
![image](https://github.com/user-attachments/assets/c209830e-e7ba-4e23-ac7d-8ea8d8d0a848)
