### ISSUE TITLE
[HOLDINGS] Holding Check with 2411

### ISSUE THREAD

**Issue by nakoale** [hvacc/Sector-File#385]
BENFE , LICUT , KPC (for rwy 12 and for 30) , KAM

**Comment by Ioannis-G** [comment]
- ALX removed
- ALX09 added
- PELAG corrected
- AGH added
- MES corrected
- TILGI (RNAV14) added
- YNN (RNAV32) corrected
- ADORI corrected
- GONSO corrected
- KAS added
- KTH added
- AKETO corrected
- KFN corrected
- KAM (RWY35L) added
- KAM (RWY17R) added
- KOS (RWY32) corrected
- KOS (RWY14) added
- LECOK added
- KPC (RWY12) added
- KPC (RWY30) added
- VEMAT added
- BEDEX corrected
- KRK corrected
- KPL (RWY05) added
- KPL (RWY23) corrected
- KOZ corrected
- LMO (RWY04R) added
- LMO (RWY22L) corrected
- MKN corrected
- MIL added
- LSV corrected
- BIFOK added
- URAKI added
- AKT added
- BESES added
- ERIBA added
- ARA (RWY18R) added
- ARA (RWY36L) added
- SUD (RWY11L) added
- SUD (RWY29R) corrected
- BEBUS added
- XANAD corrected
- SKP corrected
- SAM corrected
- KEA17 added
- KORAX added
- OSKIM added
- OLAXO added
- LADAD removed
- TSL corrected
- MKR09 (VOR34) corrected
- MKR10 (ILS16) corrected
- APZOC corrected
- NAFNU corrected
- TS626 (RNPy34) corrected
- FICLO (RNPz34) corrected
- BENFE added
- LICUT added
- ZAK corrected
- LITSI added
