### ISSUE TITLE
Ground changes pending new scenery

### ISSUE THREAD

**Issue by tasosb** [hvacc/Sector-File#56]
**Latest update : 08 OCT 2020**
1. LGMK - Taxiway Naming
2. LGMT - Apron/Stands
3. LGSM - New Stands
4. LGKV - New Stands
5. LGPZ - New Stands/Taxiways
6. LGTS - New Stands  -Pending
7. LGKR - New Stands/TaxiwayLine (AIRAC 2005)
8. LGKF - Apron/Stands/Taxiways (AIRAC 2010) SEP

**Comment by tasosb** [comment]
**Airport:** LGKO
**Publisher:** Gaya Simulations
**Release Date:** TBA

**Comment by tasosb** [comment]
![εικόνα](https://user-images.githubusercontent.com/18355854/72226066-6f2f6e00-3595-11ea-839e-546eb21e68b9.png)

**Comment by tasosb** [comment]
LGKO 
![εικόνα](https://user-images.githubusercontent.com/18355854/74455812-91672500-4e8e-11ea-93dc-d3f305e5cbdc.png)
LGKR
![εικόνα](https://user-images.githubusercontent.com/18355854/74455831-9a57f680-4e8e-11ea-9ee4-a87c95f26602.png)

**Comment by tasosb** [comment]
LGSR
![εικόνα](https://user-images.githubusercontent.com/18355854/74456483-95e00d80-4e8f-11ea-9e47-8f787b468709.png)

**Comment by nakoale** [comment]
η κοκκινη γραμμη που λειπει ειναι ο Ε

**Comment by tasosb** [comment]
All taxiways/holding points renamed: LGKF,LGMT,LGKV,LGTS, LGSM

**Comment by Vasilis-Chalipilias** [comment]
LGSK - New Apron/Stands/Taxiways Completed! 08/10/2020

**Comment by Vasilis-Chalipilias** [comment]
GroundLayout Pending due to New Sceneries will come to all platforms!

**Comment by Vasilis-Chalipilias** [comment]
**Latest update : 12 MAR 2021**
1. LGMK - Taxiway Naming [**Working in-progress**]
2. LGMT - Apron/Stands **[Waiting scenery Update]**
3. LGSM - New Stands [Waiting scenery Update]
4. LGKV - New Stands [Working in-progress]
5. LGPZ - New Stands/Taxiways Working in-progress
6. LGTS - New Stands  -Pending **[Completed]**
7. LGKR - New Stands/TaxiwayLine (AIRAC 2005) **[Waiting scenery Update]**
8. LGKF - Apron/Stands/Taxiways (AIRAC 2010) SEP **[Waiting scenery Update]**

**Comment by Vasilis-Chalipilias** [comment]
LGTS - New Stands  -Pending **[Completed]** 

- [ ]

**Comment by Vasilis-Chalipilias** [comment]
Latest update : 19 JUL 2021

LGMK - Taxiway Naming [Working in-progress] -**[Waiting scenery Update]**
LGMT - Apron/Stands **[Waiting scenery Update]**
LGSM - New Stands **[Waiting scenery Update]** 
LGKV - New Stands **[Working in-progress]**
LGPZ - New Stands/Taxiways Working in-progress
LGTS - New Stands -Pending [Completed]
LGKR - New Stands/TaxiwayLine (AIRAC 2005) **[Waiting scenery Update]**
LGKF - Apron/Stands/Taxiways (AIRAC 2010) SEP **[Waiting scenery Update]**

**Comment by Vasilis-Chalipilias** [comment]
Latest update : 08 AUG 2021

LGMK - Taxiway Naming [Working in-progress] -[Scenery Updated]
LGMT - Apron/Stands [Waiting scenery Update]
LGSM - New Stands [Scenery Update] - [Working in-progress]
LGKV - New Stands [Working in-progress]
LGTS - New Stands -Pending [Completed]
LGKR - New Stands/TaxiwayLine (AIRAC 2005) [Waiting scenery Update]
LGKF - Apron/Stands/Taxiways (AIRAC 2010) SEP [Waiting scenery Update]

**Comment by Vasilis-Chalipilias** [comment]
LGPZ - New Stands/Taxiways **[COMPLETED]**

**Comment by Vasilis-Chalipilias** [comment]
LGTS - New Stands -Pending **[Completed]**
LGKF - Apron/Stands/Taxiways (AIRAC 2010) SEP **[COMPLETED]**

**Comment by Vasilis-Chalipilias** [comment]
Latest update : 10 AUG 2021

LGMT - Apron/Stands [Waiting scenery Update] [**Groundlayout Completed**] Airac 2109

**Comment by Vasilis-Chalipilias** [comment]
Latest update : 12 AUG 2021

LGMK - Taxiway Naming - New Groundlayout - New Labels - New Profile.ASR   -[Scenery Updated] - [**Completed**]

**Comment by Vasilis-Chalipilias** [comment]
Latest update : 18 AUG 2021
LGKV - New Stands - Taxilines - Groundlayout [**Completed**]
LGAL - New Stands - Taxilines - Groundlayout [**Completed**]
LGHI - New Stands - Taxilines - Groundlayout [**Completed**]

**Comment by Vasilis-Chalipilias** [comment]
LGKR - New Stands/TaxiwayLine  [**Completed**]

**Comment by Vasilis-Chalipilias** [comment]
LGSR - New Stands/TaxiwayLine - Labels - Colors **[COMPLETED]** **Airac 2109**
