### ISSUE TITLE
[COPX] LGSR_APP - LGGG with LGAV_APP online.

### ISSUE THREAD

**Issue by nakoale** [hvacc/sector-file#98]
**Description**

Ημουν ανοιχτος σαν LGGG και το LGAV_APP ανοιχτο. το αεροσκαφος ηταν στο 350 περιπου στο ROPOX και μου ζητησε το LGSR_APP dir SNI και του εδειχνε οτι δεν ειναι επομενος controller το LGSR_APP προφανως γιατι θεωρησε οτι θα περασει απο τερματικη αθηνων. αυτο πρεπει να διορθωθει, νομιζω εχει να κανει με τα ownerships.

**Comment by tasosb** [comment]
Υπολογίζει - φαντάζομαι - πως το αεροσάφος στην κάθοδο που θα κάνει (ανεξάρτητα από το πως θα δώσεις εσύ κάθοδο) θα είναι κάτω από FL245 μέσα στην τερματική της Αθήνας. 

![εικόνα](https://user-images.githubusercontent.com/18355854/78671998-b3a67d80-78e8-11ea-80c4-33c21b670abd.png)
@nakoale : Μήπως ήταν κάπως έτσι;

**Comment by nakoale** [comment]
ναι ετσι ηταν αλλα και παλι. καπως δεν διορθωνεται αυτο; ναι μπορουμε να παρακαμψουμε την αθηνα απο τη στιγμη που ουτως ή αλλως δεν θα το κανω hand off στο lgav app αλλα κατευθειαν στο lgsr. δεν ειναι οπως με την μυκονο που περναει μεσα απτην tma

**Comment by tasosb** [comment]
> 
> 
> ναι ετσι ηταν αλλα και παλι. καπως δεν διορθωνεται αυτο; ναι μπορουμε να παρακαμψουμε την αθηνα απο τη στιγμη που ουτως ή αλλως δεν θα το κανω hand off στο lgav app αλλα κατευθειαν στο lgsr. δεν ειναι οπως με την μυκονο που περναει μεσα απτην tma

Αν κατεβει κατω απο το 245 δεν θα είναι μεσα στην TMA?
Λογικα οταν ερθει πιο κοντα στο ropox θα καταλαβει το euroscope πως δεν θα ειναι στο FL245 μεσα στην TMA της αθηνας και θα σου βγαλει το LGSR_APP

**Comment by nakoale** [comment]
ναι αλλα κατω απτο 245 θα ειναι στα ορια της tma οποτε δεν θα σε ενδιαφερει αν ειναι και μεσα , ουτως η αλλως θα βγει σε λιγο, ενω με τη μυκονο περναει μεγαλο μερος της tma below FL245. νταξει αμα δεν γινεται μικρο  το κακο.
